---
# tasks file for ansible-role-arc-client
#
#
  - name: print fgci_install
    debug: var=fgci_install

#  - name: Install FGCI repo 
#    yum: pkg=http://idris.fgi.csc.fi/fgci7/x86_64/fgci/rpms/fgci-release7-1-1.el7.noarch.rpm
#    when: ansible_distribution_major_version == "7"

  - name: apt install packages for arc-client
    apt: pkg={{ item }} state=installed
    with_items: arc_deb_client_packages

  - name: template in fetch-crl.d config
    template: src=fetch-crl.conf dest=/etc/fetch-crl.d/proxy.conf mode=0644 owner=root group=root backup=no

  - name: start fetch-crl-cron
    service: name=fetch-crl-cron state=started enabled=yes

  - name: add apt EGI trustanchors key
    apt_key: url=https://dist.eugridpma.info/distribution/igtf/current/GPG-KEY-EUGridPMA-RPM-3 state=present
    when: repo_egi_trustanchors

  - name: add apt EGI Trustanchors REPO
    apt_repository: repo='deb http://repository.egi.eu/sw/production/cas/1/current egi-igtf core' state=present
    when: repo_egi_trustanchors

  - name: apt install ca-policy-egi-core
    apt: name=ca-policy-egi-core state=present
    when: repo_egi_trustanchors
