---
# tasks file for ansible-role-arc-client
#
#
  - name: print fgci_install
    debug: var=fgci_install verbosity=1

  - name: Install FGCI repo 
    yum: pkg=http://idris.fgi.csc.fi/fgci7/x86_64/fgci/rpms/fgci-release7-1-1.el7.noarch.rpm
    when: ansible_distribution_major_version == "7"

  - name: install packages for arc-client
    yum: pkg={{ item }} state=installed
    with_items: "{{ arc_client_packages }}"

  - name: template in fetch-crl.d config
    template: src=fetch-crl.conf dest=/etc/fetch-crl.d/proxy.conf mode=0644 owner=root group=root backup=no

  - name: start fetch-crl-cron
    service: name=fetch-crl-cron state=started enabled=yes

  - name: add EGI Trustanchors REPO
    get_url: url="http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo" dest=/etc/yum.repos.d/egi-trustanchors.repo mode=0644 owner=root
    when: repo_egi_trustanchors

  - name: install repo_egi_packages
    yum: name={{ item }} state=present
    when: repo_egi_trustanchors
    with_items: "{{ repo_egi_packages }}"

  - name: check if there's a nordugrid-updates.repo
    stat: path=/etc/yum.repos.d/nordugrid-updates.repo
    register: arc_frontend_excludeCAs

  - name: exclude IGTF CAs from Nordugrid repo
    ini_file: dest=/etc/yum.repos.d/nordugrid-updates.repo
        section=nordugrid-updates
        option=exclude
        value=ca_*
        no_extra_spaces=True
        backup=yes
    when: arc_frontend_excludeCAs.stat.exists

  - name: Template ARC client.conf with sensible defaults
    template: src=client.conf.j2 dest=/etc/arc/client.conf owner=root mode=0644
    when: arc_client_conf

