---
# tasks file for ansible-role-arc-client
#
  - name: install packages for arc-client
    yum: pkg={{ item }} state=installed
    with_items: arc_client_packages

  - name: template in fetch-crl.d config
    template: src=fetch-crl.conf dest=/etc/fetch.d/proxy.conf mode=0644 owner=root group=root backup=no
